import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import contacts from "./contacts";
import organizations from "./organizations";
import businessCards from "./businessCards";
import organizationScans from "./organizationScans";
import tasks from "./tasks";
import activities from "./activities";
import opportunities from "./opportunities";
import pipelines from "./pipelines";
import notes from "./notes";
import tags from "./tags";
import reports from "./reports";
import auth from "./auth";
import adminAuth from "./adminAuth";
import adminWorkspaces from "./adminWorkspaces";
import emsProfiles from "./emsProfiles";
import adminPipelineTemplates from "./adminPipelineTemplates";
import workspacePipelineViews from "./workspacePipelineViews";
import workspaceMembers from "./workspaceMembers";
import structureScans from "./structureScans";
import adminMasterOrganizations from "./adminMasterOrganizations";
import adminMasterOrganizationRelationships from "./adminMasterOrganizationRelationships";
import adminStats from "./adminStats";
import adminMasterOrgScans from "./adminMasterOrgScans";
import adminMasterOrgDiagnostics from "./adminMasterOrgDiagnostics";
import adminAiSuggestions from "./adminAiSuggestions";
import adminMasterPromotion from "./adminMasterPromotion";
import adminContactIdentity from "./adminContactIdentity";
import adminOnboarding from "./adminOnboarding";
import adminOnboardingPresets from "./adminOnboardingPresets";
import adminDay1 from "./adminDay1";
import healthcareIntelligence from "./healthcareIntelligence";
import govcon from "./govcon";
import adminGovconDiagnostics from "./adminGovconDiagnostics";
import capture from "./capture";
import enrich from "./enrich";
import commissions from "./commissions";
import opportunityEvents from "./opportunityEvents";
import preVisitBrief from "./preVisitBrief";
import bulkImport from "./bulkImport";
import adminCmsSync from "./adminCmsSync";
import adminFacilityTypeBackfill from "./adminFacilityTypeBackfill";
import adminVerticals from "./adminVerticals";
import { authMiddleware } from "../lib/authMiddleware";
import { platformAdminMiddleware } from "../lib/platformAdminMiddleware";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", auth);
router.use("/admin", adminAuth);
router.use("/admin/workspaces", adminWorkspaces);
router.use("/admin/master-organizations", platformAdminMiddleware, adminMasterOrganizations);
router.use("/admin/master-organization-relationships", platformAdminMiddleware, adminMasterOrganizationRelationships);
router.use("/admin/stats", adminStats);
router.use("/admin/pipeline-templates", platformAdminMiddleware, adminPipelineTemplates);
router.use("/admin/master-org-scans", platformAdminMiddleware, adminMasterOrgScans);
router.use("/admin/diagnostics", platformAdminMiddleware, adminMasterOrgDiagnostics);
router.use("/admin/govcon-diagnostics", platformAdminMiddleware, adminGovconDiagnostics);
router.use("/admin/ai-suggestions", platformAdminMiddleware, adminAiSuggestions);
router.use("/admin/master-promotion", platformAdminMiddleware, adminMasterPromotion);
router.use("/admin/contact-identity", platformAdminMiddleware, adminContactIdentity);
router.use("/admin/onboarding/presets", platformAdminMiddleware, adminOnboardingPresets);
router.use("/admin/onboarding", platformAdminMiddleware, adminOnboarding);
router.use("/admin/workspaces", platformAdminMiddleware, adminDay1);
router.use("/admin/cms-sync", platformAdminMiddleware, adminCmsSync);
router.use("/admin/facility-type-backfill", platformAdminMiddleware, adminFacilityTypeBackfill);
router.use("/admin/verticals", platformAdminMiddleware, adminVerticals);
router.use(authMiddleware);
router.use(storageRouter);

router.use("/contacts", contacts);
router.use("/organizations", organizations);
router.use("/organizations/:id", healthcareIntelligence);
router.use("/business-cards", businessCards);
router.use("/organization-scans", organizationScans);
router.use("/tasks", tasks);
router.use("/activities", activities);
router.use("/opportunities", opportunities);
router.use("/pipelines", pipelines);
router.use("/notes", notes);
router.use("/tags", tags);
router.use("/reports", reports);
router.use(emsProfiles);
router.use("/workspaces", workspaceMembers);

router.use("/structure-scans", structureScans);

router.use("/govcon", govcon);

router.use("/capture", capture);
router.use("/enrich", enrich);
router.use("/commissions", commissions);
router.use("/opportunity-events", opportunityEvents);
router.use("/organizations/:id", preVisitBrief);
router.use("/bulk-import", bulkImport);

router.use("/workspaces/:workspaceId/pipeline-views", workspacePipelineViews);

export default router;
