// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/events/GlobalPlusMenu.tsx": () => import("../components/mockups/events/GlobalPlusMenu.tsx"),
  "./components/mockups/events/OpportunityEventForm.tsx": () => import("../components/mockups/events/OpportunityEventForm.tsx"),
  "./components/mockups/events/OpportunityEventReview.tsx": () => import("../components/mockups/events/OpportunityEventReview.tsx"),
  "./components/mockups/events/PreVisitBrief.tsx": () => import("../components/mockups/events/PreVisitBrief.tsx"),
  "./components/mockups/orgs/OrgDetailCurrent.tsx": () => import("../components/mockups/orgs/OrgDetailCurrent.tsx"),
  "./components/mockups/orgs/OrgDetailProposed.tsx": () => import("../components/mockups/orgs/OrgDetailProposed.tsx"),
  "./components/mockups/orgs/OrgDetailTabActivity.tsx": () => import("../components/mockups/orgs/OrgDetailTabActivity.tsx"),
  "./components/mockups/orgs/OrgDetailTabContacts.tsx": () => import("../components/mockups/orgs/OrgDetailTabContacts.tsx"),
  "./components/mockups/orgs/OrgDetailTabHierarchy.tsx": () => import("../components/mockups/orgs/OrgDetailTabHierarchy.tsx"),
  "./components/mockups/orgs/OrgDetailTabOverview.tsx": () => import("../components/mockups/orgs/OrgDetailTabOverview.tsx"),
  "./components/mockups/orgs/OrgsTabCurrent.tsx": () => import("../components/mockups/orgs/OrgsTabCurrent.tsx"),
  "./components/mockups/orgs/OrgsTabProposed.tsx": () => import("../components/mockups/orgs/OrgsTabProposed.tsx"),
  "./components/mockups/opp-eye/CurrentCardScan.tsx": () => import("../components/mockups/opp-eye/CurrentCardScan.tsx"),
  "./components/mockups/opp-eye/CurrentOrgScan.tsx": () => import("../components/mockups/opp-eye/CurrentOrgScan.tsx"),
  "./components/mockups/opp-eye/HierarchyViewer.tsx": () => import("../components/mockups/opp-eye/HierarchyViewer.tsx"),
  "./components/mockups/opp-eye/HierarchyViewerV2.tsx": () => import("../components/mockups/opp-eye/HierarchyViewerV2.tsx"),
  "./components/mockups/opp-eye/OpportunityEye.tsx": () => import("../components/mockups/opp-eye/OpportunityEye.tsx")
};
