// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/opp-eye/CurrentCardScan.tsx": () => import("../components/mockups/opp-eye/CurrentCardScan.tsx"),
  "./components/mockups/opp-eye/CurrentOrgScan.tsx": () => import("../components/mockups/opp-eye/CurrentOrgScan.tsx"),
  "./components/mockups/opp-eye/HierarchyViewer.tsx": () => import("../components/mockups/opp-eye/HierarchyViewer.tsx"),
  "./components/mockups/opp-eye/HierarchyViewerV2.tsx": () => import("../components/mockups/opp-eye/HierarchyViewerV2.tsx"),
  "./components/mockups/opp-eye/OpportunityEye.tsx": () => import("../components/mockups/opp-eye/OpportunityEye.tsx"),
  "./components/mockups/orgs/OrgDetailCurrent.tsx": () => import("../components/mockups/orgs/OrgDetailCurrent.tsx"),
  "./components/mockups/orgs/OrgDetailProposed.tsx": () => import("../components/mockups/orgs/OrgDetailProposed.tsx"),
  "./components/mockups/orgs/OrgsTabCurrent.tsx": () => import("../components/mockups/orgs/OrgsTabCurrent.tsx"),
  "./components/mockups/orgs/OrgsTabProposed.tsx": () => import("../components/mockups/orgs/OrgsTabProposed.tsx")
};
